https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb

1. Import the numpy package under the name np (★☆☆)


In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.26.4


In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:

3. Create a null vector of size 10 (★☆☆)

In [7]:
a = np.zeros(10)

In [8]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [9]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
a= np.zeros(10)

In [20]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
a[4] = 1

In [22]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [24]:
a = np.arange(10,50)

In [25]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) (★☆☆)    

In [26]:
a = np.arange(5)

In [30]:
a

array([0, 1, 2, 3, 4])

In [28]:
b = a[::-1]

In [29]:
b

array([4, 3, 2, 1, 0])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [31]:
a = np.arange(9).reshape(3,3)

In [32]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)


In [34]:
nz = np.nonzero([1,2,0,0,4,0])

In [36]:
print(nz)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)


In [37]:
a = np.eye(3)

In [38]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)


In [39]:
rng = np.random.default_rng()

In [40]:
a = rng.random((3,3,3))

In [44]:
print(a)

[[[0.05656509 0.22863108 0.96395819]
  [0.26616944 0.01623117 0.39592142]
  [0.87899078 0.13091401 0.59357051]]

 [[0.57893564 0.45244507 0.78149265]
  [0.96663081 0.09105661 0.80392795]
  [0.61367732 0.67445206 0.38435191]]

 [[0.04588238 0.21861076 0.47452393]
  [0.43110716 0.16571683 0.51902167]
  [0.74335485 0.55976507 0.76756836]]]


In [42]:
z = np.random.random((3,3,3))

In [43]:
print(z)

[[[0.31435589 0.59169809 0.94943151]
  [0.11496453 0.81810385 0.25313365]
  [0.71157221 0.76277931 0.40802927]]

 [[0.62557833 0.15555981 0.56846989]
  [0.672952   0.50565224 0.241783  ]
  [0.04262191 0.59622031 0.2692115 ]]

 [[0.9775806  0.97442068 0.23013242]
  [0.08950068 0.45667649 0.90283334]
  [0.22790133 0.87204519 0.20231085]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [46]:
a = np.random.random((10,10))

In [47]:
print(a)

[[0.69443041 0.51103665 0.83897994 0.63986484 0.70382445 0.77847734
  0.02556905 0.24672639 0.72487317 0.6026688 ]
 [0.10522512 0.56706767 0.27428163 0.32169138 0.08283209 0.5233643
  0.61168689 0.96743109 0.68896822 0.56271384]
 [0.25369914 0.3668484  0.52402953 0.75974327 0.50445729 0.83273767
  0.75180198 0.35750645 0.45303125 0.57379045]
 [0.54913166 0.70783866 0.5001888  0.78584256 0.19591964 0.54095156
  0.75436679 0.48083283 0.0489669  0.56256841]
 [0.90887385 0.64029562 0.57503277 0.66330836 0.51105544 0.71847334
  0.15562007 0.471393   0.87826817 0.3721805 ]
 [0.3691381  0.53861202 0.38935012 0.5845954  0.10164037 0.60753549
  0.24644641 0.3923411  0.77444142 0.49545782]
 [0.90211928 0.71095823 0.29733526 0.06112026 0.59658987 0.8304293
  0.9002498  0.23093588 0.30343037 0.84160005]
 [0.51935565 0.79409534 0.82375025 0.54276917 0.19554491 0.52544424
  0.95832933 0.27045731 0.01314069 0.22199334]
 [0.39426131 0.00150754 0.41484874 0.62664651 0.41663533 0.16047179
  0.45112934 0

In [48]:
np.min(a)

0.0015075398337006662

In [49]:
np.max(a)

0.9799644686632464

In [50]:
min = a.min()
print(min)

0.0015075398337006662


In [51]:
max = a.max()
print(max)

0.9799644686632464


14. Create a random vector of size 30 and find the mean value (★☆☆)


In [53]:
a = np.random.random(30)
print(a)

[0.48518678 0.0452797  0.66160015 0.54076008 0.23000658 0.10759169
 0.92705023 0.22336816 0.35354282 0.8228243  0.17072443 0.42968343
 0.39208446 0.69364936 0.88731361 0.64704619 0.37677571 0.41479197
 0.63781573 0.90614502 0.38495383 0.54103034 0.93920466 0.90596104
 0.44375446 0.30509165 0.64976593 0.5448095  0.80707698 0.05038177]


In [54]:
mean = a.mean()
print(mean)

0.517509018222952


In [55]:
a.mean()

0.517509018222952

In [56]:
np.mean(a)

0.517509018222952

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [62]:
a = np.ones(9).reshape(3,3)
print(a)
a[1][1] = 0
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [63]:
Z = np.ones((10,10))
print(Z)
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [65]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆) => ???????   
0 * np.nan   
np.nan == np.nan   
np.inf > np.nan   
np.nan - np.nan   
np.nan in set([np.nan])   
0.3 == 3 * 0.1   

In [66]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [77]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [78]:
x = np.zeros((5,5), dtype='int64')
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [79]:
x[1][0] = 1
x[2][1] = 2
x[3][2] = 3
x[4][3] = 4
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


22. Normalize a 5x5 random matrix (★☆☆)


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


26. What is the output of the following script? (★☆☆)   
# Author: Jake VanderPlas   

print(sum(range(5),-1))   
from numpy import *   
print(sum(range(5),-1))   

27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)   
Z**Z   
2 << Z >> 2   
Z <- Z   
1j*Z   
Z/1/1   
Z<Z>Z   

28. What are the result of the following expressions? (★☆☆)   
np.array(0) / np.array(0)   
np.array(0) // np.array(0)   
np.array([np.nan]).astype(int).astype(float)

29. How to round away from zero a float array ? (★☆☆)


30. How to find common values between two arrays? (★☆☆)


31. How to ignore all numpy warnings (not recommended)? (★☆☆)


32. Is the following expressions true? (★☆☆)   
np.sqrt(-1) == np.emath.sqrt(-1)

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


34. How to get all the dates corresponding to the month of July 2016? (★★☆)


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


40. Create a random vector of size 10 and sort it (★★☆)


41. How to sum a small array faster than np.sum? (★★☆)


42. Consider two random array A and B, check if they are equal (★★☆)


43. Make an array immutable (read-only) (★★☆)


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)


48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


49. How to print all the values of an array? (★★☆)


50. How to find the closest value (to a given scalar) in a vector? (★★☆)


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


53. How to convert a float (32 bits) array into an integer (32 bits) in place?


54. How to read the following file? (★★☆)   
1, 2, 3, 4, 5   
6,  ,  , 7, 8   
 ,  , 9,10,11   

55. What is the equivalent of enumerate for numpy arrays? (★★☆)


56. Generate a generic 2D Gaussian-like array (★★☆)


57. How to randomly place p elements in a 2D array? (★★☆)


58. Subtract the mean of each row of a matrix (★★☆)


59. How to sort an array by the nth column? (★★☆)



60. How to tell if a given 2D array has null columns? (★★☆)


61. Find the nearest value from a given value in an array (★★☆)


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

63. Create an array class that has a name attribute (★★☆)


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)


69. How to get the diagonal of a dot product? (★★★)


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)



72. How to swap two rows of an array? (★★★)


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)


75. How to compute averages using a sliding window over an array? (★★★)


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)



80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)



81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)


82. Compute a matrix rank (★★★)


83. How to find the most frequent value in an array?


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)


88. How to implement the Game of Life using numpy arrays? (★★★)



89. How to get the n largest values of an array (★★★)


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)


91. How to create a record array from a regular array? (★★★)


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


95. Convert a vector of ints into a matrix binary representation (★★★)


96. Given a two dimensional array, how to extract unique rows? (★★★)


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
